# Generated by Django 3.1.7 on 2022-05-13 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20201006_0125'),
        ('category', '0002_auto_20220203_1157'),
    ]

    operations = [
    ]
